Squash feature/CNC-229-implement-apidoc2swagger-converter
CN-Consult/FileCloud-PHP pull request #1
Opened 2017-03-15 15:33 UTC by PStiemer

## Contents
The apidoc2swagger class creates a swagger compatible json file from an apidoc generated api documentation.
It is especially designed for the filecloud user api. It will probably not work for other apis generated by apidoc.

## Tests done
I took the filecloud api documentation and used this class to generate a json file that is swagger ready.
Swagger automatically generates a documentation and displays errors if there are any.
![image](https://cloud.githubusercontent.com/assets/13750648/23956173/45af2b2e-099c-11e7-8d14-68caaa4f3a2f.png)

Furthermore i used the swagger online editor to log in to filecloud, which worked.

**Squash message:**
```
Implement apidoc2swagger class which converts a filecloud api generated by apidoc to a swagger formatted api documentation.
```

2017-03-20 16:06 UTC, Shyru requested changes
Looks very good in general! :+1:

2017-03-20 16:06 UTC, Shyru commented on apidoc2swagger/apidoc2swagger.php
> + *
Please add a short-reference to the license this code is in.
Did we already decide on a license?  If not I would propose MIT.
Then you could add a sentence like this to the docblock:
```
This file is part of FileCloud-PHP.
Please check the file LICENSE for information about the license.
```

Here is an example how other open-source projects do this:
https://github.com/symfony/console/blob/master/Terminal.php

2017-03-20 16:06 UTC, Shyru commented on apidoc2swagger/apidoc2swagger.php
> + */
Add more description on how to use the class. For example:
``` Use the method convert() to convert an apidoc-file to a swagger-file```.

2017-03-20 16:06 UTC, Shyru commented on apidoc2swagger/apidoc2swagger.php
> + */
Since this file does not only contain a class, but is a script that can be called you should also document the parameters it uses.

2017-03-20 16:06 UTC, Shyru commented on apidoc2swagger/apidoc2swagger.php
> +    function createResponseReference($_apiCall)
Shouldn't this be `private`?

2017-03-20 16:06 UTC, Shyru commented on apidoc2swagger/apidoc2swagger.php
> +    function createResponseDefinitions($_apiCall)
Shouldn't this be `private`?

2017-03-21 12:20 UTC, PStiemer commented on apidoc2swagger/apidoc2swagger.php
> + *
Yes i agree with the MIT license. But since you are the repository owner you have to add that license i think.

2017-03-21 13:14 UTC, Shyru requested changes
Looks good, but please also add an MIT-License to the repository root as "LICENSE".

2017-03-21 13:20 UTC, PStiemer commented
Added Apache License instead of the MIT license because swagger is using the apache license.

2017-03-21 15:10 UTC, Shyru approved these changes

2017-03-21 15:11 UTC, merged